baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "AxiomAbsolute"
author = "AxiomAbsolute"
contentdir = "content"
publishdir = "public"
description = "Thoughts on programming, language, and maths"

[indexes]
  category = "categories"
  tag = "tags"
[Params]
  AuthorName = "Devon"
  github = "axiomabsolute"
  email = "axiomabsolute@gmail.com"
  cover = "https://static.pexels.com/photos/7462/pexels-photo.jpeg"
  description = "Thoughts on programming, language, and maths"